sudo: false
language: ruby
rvm:
  - 2.3.1
services:
  - postgresql
before_install: gem install bundler -v 1.13.6
install:
  - bundle install
before_script:
  - cp config/database.yml.travis config/database.yml
